version: '1.4.5.{build}'

image:
  - Visual Studio 2017

skip_commits:
  message: /\[ci skip\]/

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"

nuget:
  account_feed: true
  project_feed: true

platform: Mixed

init:

configuration:
  - Debug
  - Release

install:
  - cmd: git submodule update --init --recursive

before_build:
  nuget restore OpenBVE.sln

build:
  project: C:\projects\OpenBVExp\OpenBVE.sln

after_build:

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
